class exhibitor::params {

  $version     = '1.5.2'
  $zk_version  = '3.4.6'
  $zk_mirror   = 'https://www.apache.org/dist/zookeeper'
  $zk_home_dir = '/opt/zookeeper'
  $zk_log_dir  = '/var/log/zookeeper'
  $zk_data_dir = '/var/lib/zookeeper'
  $user        = 'zookeeper'
  $group       = 'zookeeper'
  $install_dir = '/opt/exhibitor'
  $defaults    = {
    'auto-manage-instances'                     => '1',
    'auto-manage-instances-settling-period-ms'  => '15000',
    'auto-manage-instances-fixed-ensemble-size' => '1',
    'check-ms'                                  => '30000',
    'client-port'                               => '2181',
    'connect-port'                              => '2888',
    'election-port'                             => '3888',
    'cleanup-period-ms'                         => '300000',
    'cleanup-max-files'                         => '20',
    'observer-threshold'                        => '0',
    'zoo-cfg-extra'                             => 'tickTime\=2000&initLimit\=10&syncLimit\=5&quorumListenOnAllIPs\=true',
    'zookeeper-install-directory'               => '/opt/zookeeper',
    'zookeeper-data-directory'                  => '/var/lib/zookeeper',
    'zookeeper-log-directory'                   => '/var/log/zookeeper',
    'log-index-directory'                       => '/var/lib/zookeeper',
  }

  $properties  = {
    'com.netflix.exhibitor-rolling-hostnames'                                 => '',
    'com.netflix.exhibitor-rolling-hostnames-index'                           => '',
    'com.netflix.exhibitor-rolling.auto-manage-instances'                     => '1',
    'com.netflix.exhibitor-rolling.auto-manage-instances-apply-all-at-once'   => '1',
    'com.netflix.exhibitor-rolling.auto-manage-instances-fixed-ensemble-size' => '1',
    'com.netflix.exhibitor-rolling.auto-manage-instances-settling-period-ms'  => '30000',
    'com.netflix.exhibitor-rolling.backup-extra'                              => '',
    'com.netflix.exhibitor-rolling.backup-max-store-ms'                       => '86400000',
    'com.netflix.exhibitor-rolling.backup-period-ms'                          => '60000',
    'com.netflix.exhibitor-rolling.check-ms'                                  => '30000',
    'com.netflix.exhibitor-rolling.cleanup-max-files'                         => '20',
    'com.netflix.exhibitor-rolling.cleanup-period-ms'                         => '43200000',
    'com.netflix.exhibitor-rolling.client-port'                               => '2181',
    'com.netflix.exhibitor-rolling.connect-port'                              => '2888',
    'com.netflix.exhibitor-rolling.election-port'                             => '3888',
    'com.netflix.exhibitor-rolling.java-environment'                          => '',
    'com.netflix.exhibitor-rolling.log-index-directory'                       => '',
    'com.netflix.exhibitor-rolling.log4j-properties'                          => '',
    'com.netflix.exhibitor-rolling.observer-threshold'                        => '0',
    'com.netflix.exhibitor-rolling.servers-spec'                              => '',
    'com.netflix.exhibitor-rolling.zoo-cfg-extra'                             => 'tickTime\=2000&initLimit\=10&syncLimit\=5&quorumListenOnAllIPs\=true',
    'com.netflix.exhibitor-rolling.zookeeper-data-directory'                  => '/var/lib/zookeeper',
    'com.netflix.exhibitor-rolling.zookeeper-install-directory'               => '/opt/zookeeper',
    'com.netflix.exhibitor-rolling.zookeeper-log-directory'                   => '',
    'com.netflix.exhibitor.auto-manage-instances'                             => '1',
    'com.netflix.exhibitor.auto-manage-instances-apply-all-at-once'           => '1',
    'com.netflix.exhibitor.auto-manage-instances-fixed-ensemble-size'         => '1',
    'com.netflix.exhibitor.auto-manage-instances-settling-period-ms'          => '15000',
    'com.netflix.exhibitor.backup-extra'                                      => '',
    'com.netflix.exhibitor.backup-max-store-ms'                               => '86400000',
    'com.netflix.exhibitor.backup-period-ms'                                  => '60000',
    'com.netflix.exhibitor.check-ms'                                          => '30000',
    'com.netflix.exhibitor.cleanup-max-files'                                 => '20',
    'com.netflix.exhibitor.cleanup-period-ms'                                 => '300000',
    'com.netflix.exhibitor.client-port'                                       => '2181',
    'com.netflix.exhibitor.connect-port'                                      => '2888',
    'com.netflix.exhibitor.election-port'                                     => '3888',
    'com.netflix.exhibitor.java-environment'                                  => '',
    'com.netflix.exhibitor.log-index-directory'                               => '',
    'com.netflix.exhibitor.log4j-properties'                                  => '',
    'com.netflix.exhibitor.observer-threshold'                                => '0',
    'com.netflix.exhibitor.servers-spec'                                      => '',
    'com.netflix.exhibitor.zoo-cfg-extra'                                     => 'syncLimit\=5&tickTime\=2000&initLimit\=10&quorumListenOnAllIPs\=true',
    'com.netflix.exhibitor.zookeeper-data-directory'                          => '/var/lib/zookeeper',
    'com.netflix.exhibitor.zookeeper-install-directory'                       => '/opt/zookeeper',
    'com.netflix.exhibitor.zookeeper-log-directory'                           => '',
  }
}
